CREATE DATABASE LUKAS_DESA
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE LUKAS_DESA;

CREATE TABLE usuarios (
  ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
  NOMBRE VARCHAR(100) NOT NULL,
  APELLIDO VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL UNIQUE,
  CONTRASENA VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE ingreso (
  ID_INGRESO INT AUTO_INCREMENT PRIMARY KEY,
  TITULO_INGRESO VARCHAR(255) NOT NULL,
  MONTO_INGRESO DECIMAL(10,2) NOT NULL,
  ID_USUARIO INT NOT NULL,
  FECHA_INGRESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO)
);

CREATE TABLE gastos (
  ID_GASTO INT AUTO_INCREMENT PRIMARY KEY,
  TITULO_GASTO VARCHAR(255) NOT NULL,
  MONTO_GASTO DECIMAL(10,2) NOT NULL,
  PAGADO BOOLEAN DEFAULT FALSE,
  ID_USUARIO INT NOT NULL,
  FECHA_GASTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO)
);

DROP TABLE IF EXISTS DIM_DATE

CREATE TABLE DIM_FECHA (
    FECHA_ID              INT PRIMARY KEY,          -- YYYYMMDD
    FECHA_COMPLETA        DATE NOT NULL UNIQUE,
    ANIO                  INT NOT NULL,
    MES                   INT NOT NULL,
    ORDEN_MES             INT NOT NULL,              -- 1 a 12
    NOMBRE_MES            VARCHAR(20) NOT NULL,
    SEMANA_ANIO           INT NOT NULL,              -- semana ISO
    SEMANA_MES            INT NOT NULL,              -- semana dentro del mes
    DIA                   INT NOT NULL,
    DIA_SEMANA            INT NOT NULL,              -- 1=Lunes, 7=Domingo
    NOMBRE_DIA_SEMANA     VARCHAR(20) NOT NULL,
    DIA_ANIO              INT NOT NULL,
    TRIMESTRE             INT NOT NULL,
    SEMESTRE              INT NOT NULL,
    ES_FIN_DE_SEMANA      BOOLEAN NOT NULL
);

INSERT INTO DIM_FECHA (
    FECHA_ID,
    FECHA_COMPLETA,
    ANIO,
    MES,
    ORDEN_MES,
    NOMBRE_MES,
    SEMANA_ANIO,
    SEMANA_MES,
    DIA,
    DIA_SEMANA,
    NOMBRE_DIA_SEMANA,
    DIA_ANIO,
    TRIMESTRE,
    SEMESTRE,
    ES_FIN_DE_SEMANA
)
SELECT
    DATE_FORMAT(DATE('2025-01-01') + INTERVAL N DAY, '%Y%m%d') + 0 AS FECHA_ID,
    DATE('2025-01-01') + INTERVAL N DAY                             AS FECHA_COMPLETA,
    YEAR(DATE('2025-01-01') + INTERVAL N DAY)                       AS ANIO,
    MONTH(DATE('2025-01-01') + INTERVAL N DAY)                      AS MES,
    MONTH(DATE('2025-01-01') + INTERVAL N DAY)                      AS ORDEN_MES,
    MONTHNAME(DATE('2025-01-01') + INTERVAL N DAY)                  AS NOMBRE_MES,
    WEEK(DATE('2025-01-01') + INTERVAL N DAY, 3)                    AS SEMANA_ANIO,
    WEEK(DATE('2025-01-01') + INTERVAL N DAY, 3)
      - WEEK(DATE_SUB(DATE('2025-01-01') + INTERVAL N DAY,
            INTERVAL DAY(DATE('2025-01-01') + INTERVAL N DAY) - 1 DAY), 3) + 1
                                                                    AS SEMANA_MES,
    DAY(DATE('2025-01-01') + INTERVAL N DAY)                        AS DIA,
    WEEKDAY(DATE('2025-01-01') + INTERVAL N DAY) + 1                AS DIA_SEMANA,
    DAYNAME(DATE('2025-01-01') + INTERVAL N DAY)                    AS NOMBRE_DIA_SEMANA,
    DAYOFYEAR(DATE('2025-01-01') + INTERVAL N DAY)                  AS DIA_ANIO,
    QUARTER(DATE('2025-01-01') + INTERVAL N DAY)                    AS TRIMESTRE,
    IF(MONTH(DATE('2025-01-01') + INTERVAL N DAY) <= 6, 1, 2)       AS SEMESTRE,
    IF(WEEKDAY(DATE('2025-01-01') + INTERVAL N DAY) >= 5, 1, 0)     AS ES_FIN_DE_SEMANA
FROM (
    SELECT a.N + b.N * 10 + c.N * 100 AS N
    FROM (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
    CROSS JOIN
         (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
          UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    CROSS JOIN
         (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3) c
) NUMEROS
WHERE DATE('2025-01-01') + INTERVAL N DAY <= '2025-12-31';

SELECT * 
FROM DIM_FECHA 
WHERE ANIO = 2025;
-- Resultado esperado: 365

UPDATE DIM_FECHA
SET NOMBRE_MES = CASE NOMBRE_MES
    WHEN 'January'   THEN 'Enero'
    WHEN 'February'  THEN 'Febrero'
    WHEN 'March'     THEN 'Marzo'
    WHEN 'April'     THEN 'Abril'
    WHEN 'May'       THEN 'Mayo'
    WHEN 'June'      THEN 'Junio'
    WHEN 'July'      THEN 'Julio'
    WHEN 'August'    THEN 'Agosto'
    WHEN 'September' THEN 'Septiembre'
    WHEN 'October'   THEN 'Octubre'
    WHEN 'November'  THEN 'Noviembre'
    WHEN 'December'  THEN 'Diciembre'
    ELSE NOMBRE_MES
END;

UPDATE DIM_FECHA
SET NOMBRE_DIA_SEMANA = CASE NOMBRE_DIA_SEMANA
    WHEN 'Monday'    THEN 'Lunes'
    WHEN 'Tuesday'   THEN 'Martes'
    WHEN 'Wednesday' THEN 'Miércoles'
    WHEN 'Thursday'  THEN 'Jueves'
    WHEN 'Friday'    THEN 'Viernes'
    WHEN 'Saturday'  THEN 'Sábado'
    WHEN 'Sunday'    THEN 'Domingo'
    ELSE NOMBRE_DIA_SEMANA
END;

