-- CREAR ESQUEMA
CREATE SCHEMA IF NOT EXISTS "LUKAS";

-- CREAR TABLA CON NOMBRES REALMENTE EN MAYÚSCULAS
CREATE TABLE "LUKAS"."USUARIOS" (
  "UUID"       UUID         DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  "NOMBRE"     TEXT         NOT NULL,
  "APELLIDOS"  TEXT         NOT NULL,
  "EMAIL"      TEXT         NOT NULL UNIQUE,
  "CONTRASENA" TEXT         NOT NULL,
  "CREATED_AT" TIMESTAMPTZ  DEFAULT NOW()
);

ALTER TABLE "LUKAS"."USUARIOS" DISABLE ROW LEVEL SECURITY;
